package io.loli.box.service;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;

/**
 * All storage service should implements this interface
 * 
 * @author choco
 *
 */
public interface StorageService {
    /**
     * Upload an image file
     * 
     * @param file file to upload. After uploaded, file name will be changed to
     *            nano time.
     * @return A relative url str generated by storage service
     * @throws IOException Will be throwed while IO error occurred
     */
    public String upload(File file) throws IOException;

    /**
     * Upload an InputStream with file name
     * 
     * @param is file to upload. After uploaded, file name will be changed to
     *            nano time.
     * @param filename origin name of this file
     * @return A relative url str generated by storage service
     * @throws IOException Will be throwed while IO error occurred
     */
    String upload(InputStream is, String filename) throws IOException;

}
