package io.loli.box.service;

import java.io.File;
import java.io.IOException;
import java.net.URL;

/**
 * All storage service should implements this interface
 * 
 * @author choco
 *
 */
public interface StorageService {
    /**
     * Upload an image file
     * 
     * @param file file to upload. File name musted be shorted
     * @return A url generated by storage service
     * @throws IOException Will be throwed while IO error occurred
     */
    URL upload(File file) throws IOException;
}
